### ISSUE TITLE
Integration of the created parser and tokenizer into the system

### ISSUE THREAD

**Issue by WinnerJust** [InnoSWP/InnoMemorizerApp#4]
Now it is necessary to implement separately developed functionality into the created application skeleton: a parser and a tokenizer.
At the same time, the development of the general functionality of the first page is being completed.

**Comment by sabonlise** [comment]
Resolved with 511dd22654dd8303f744b6376089e4c8dbb05922. Also, added manual parsing of sentences in case of API errors.
